pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - author=depfu[bot]
      - base=main
    actions:
      merge:
        method: squash
